import asyncHandler from 'express-async-handler';
import DietPlan from '../models/DietPlan.js';
import User from '../models/User.js';

// @desc    Get user diet plans
// @route   GET /api/diet
// @access  Private
export const getDietPlans = asyncHandler(async (req, res) => {
  const pageSize = 10;
  const page = Number(req.query.pageNumber) || 1;
  const isActive = req.query.active === 'true';

  let query = { user: req.user._id };

  if (isActive !== undefined) {
    query.isActive = isActive;
  }

  const count = await DietPlan.countDocuments(query);
  const dietPlans = await DietPlan.find(query)
    .sort({ createdAt: -1 })
    .limit(pageSize)
    .skip(pageSize * (page - 1));

  res.json({
    dietPlans,
    page,
    pages: Math.ceil(count / pageSize),
    total: count,
  });
});

// @desc    Get single diet plan
// @route   GET /api/diet/:id
// @access  Private
export const getDietPlan = asyncHandler(async (req, res) => {
  const dietPlan = await DietPlan.findById(req.params.id);

  if (dietPlan) {
    // Check authorization
    if (dietPlan.user.toString() !== req.user._id.toString() && req.user.role !== 'admin') {
      res.status(401);
      throw new Error('Not authorized to view this diet plan');
    }

    res.json(dietPlan);
  } else {
    res.status(404);
    throw new Error('Diet plan not found');
  }
});

// @desc    Create diet plan
// @route   POST /api/diet
// @access  Private
export const createDietPlan = asyncHandler(async (req, res) => {
  const {
    title,
    description,
    duration,
    goals,
    dietaryPreferences,
    restrictions,
    currentStats,
    dailyMeals,
    weeklyRoutine,
    supplements,
  } = req.body;

  // Deactivate existing active plan
  await DietPlan.updateMany(
    { user: req.user._id, isActive: true },
    { isActive: false }
  );

  const dietPlan = new DietPlan({
    user: req.user._id,
    title,
    description,
    duration,
    goals,
    dietaryPreferences,
    restrictions,
    currentStats,
    dailyMeals,
    weeklyRoutine,
    supplements,
    isAIGenerated: false, // User-created
  });

  const createdDietPlan = await dietPlan.save();
  res.status(201).json(createdDietPlan);
});

// @desc    Generate AI diet plan
// @route   POST /api/diet/generate
// @access  Private
export const generateDietPlan = asyncHandler(async (req, res) => {
  const { goals, preferences, restrictions, currentStats } = req.body;

  // Get user profile data
  const user = await User.findById(req.user._id);

  // Deactivate existing active plan
  await DietPlan.updateMany(
    { user: req.user._id, isActive: true },
    { isActive: false }
  );

  // AI logic would go here - for now, create a basic structure
  const aiPrompt = `Generate diet plan for goals: ${goals.join(', ')}, preferences: ${preferences?.join(', ') || 'none'}, restrictions: ${restrictions?.join(', ') || 'none'}`;

  // Create a sample AI-generated diet plan
  const dietPlan = new DietPlan({
    user: req.user._id,
    title: `AI-Generated Diet Plan for ${goals.join(' & ')}`,
    description: 'Personalized diet plan generated by AI based on your goals and preferences',
    duration: 30,
    goals,
    dietaryPreferences: preferences || [],
    restrictions: restrictions || [],
    currentStats: currentStats || {
      height: user.height,
      weight: user.weight,
      age: user.age,
    },
    dailyMeals: generateSampleMeals(goals, preferences),
    weeklyRoutine: {
      exercise: ['30 min walk', 'Yoga session', 'Light stretching'],
      meditation: ['10 min morning meditation'],
      sleep: '7-8 hours',
    },
    supplements: [
      {
        name: 'Multivitamin',
        dosage: '1 tablet',
        timing: 'With breakfast',
        benefits: 'General nutritional support',
      },
    ],
    isAIGenerated: true,
    aiPrompt,
  });

  const createdDietPlan = await dietPlan.save();
  res.status(201).json(createdDietPlan);
});

// @desc    Update diet plan
// @route   PUT /api/diet/:id
// @access  Private
export const updateDietPlan = asyncHandler(async (req, res) => {
  const dietPlan = await DietPlan.findById(req.params.id);

  if (dietPlan) {
    // Check authorization
    if (dietPlan.user.toString() !== req.user._id.toString() && req.user.role !== 'admin') {
      res.status(401);
      throw new Error('Not authorized to update this diet plan');
    }

    Object.assign(dietPlan, req.body);
    const updatedDietPlan = await dietPlan.save();
    res.json(updatedDietPlan);
  } else {
    res.status(404);
    throw new Error('Diet plan not found');
  }
});

// @desc    Delete diet plan
// @route   DELETE /api/diet/:id
// @access  Private
export const deleteDietPlan = asyncHandler(async (req, res) => {
  const dietPlan = await DietPlan.findById(req.params.id);

  if (dietPlan) {
    // Check authorization
    if (dietPlan.user.toString() !== req.user._id.toString() && req.user.role !== 'admin') {
      res.status(401);
      throw new Error('Not authorized to delete this diet plan');
    }

    await dietPlan.remove();
    res.json({ message: 'Diet plan removed' });
  } else {
    res.status(404);
    throw new Error('Diet plan not found');
  }
});

// @desc    Add progress entry
// @route   POST /api/diet/:id/progress
// @access  Private
export const addProgress = asyncHandler(async (req, res) => {
  const dietPlan = await DietPlan.findById(req.params.id);

  if (dietPlan) {
    // Check authorization
    if (dietPlan.user.toString() !== req.user._id.toString() && req.user.role !== 'admin') {
      res.status(401);
      throw new Error('Not authorized to update this diet plan');
    }

    const progressEntry = {
      date: new Date(),
      ...req.body,
    };

    dietPlan.progress.push(progressEntry);
    await dietPlan.save();

    res.status(201).json(progressEntry);
  } else {
    res.status(404);
    throw new Error('Diet plan not found');
  }
});

// @desc    Get diet plan progress
// @route   GET /api/diet/:id/progress
// @access  Private
export const getProgress = asyncHandler(async (req, res) => {
  const dietPlan = await DietPlan.findById(req.params.id);

  if (dietPlan) {
    // Check authorization
    if (dietPlan.user.toString() !== req.user._id.toString() && req.user.role !== 'admin') {
      res.status(401);
      throw new Error('Not authorized to view this diet plan');
    }

    res.json(dietPlan.progress);
  } else {
    res.status(404);
    throw new Error('Diet plan not found');
  }
});

// Helper function to generate sample meals
const generateSampleMeals = (goals, preferences) => {
  const meals = [];
  const isVegetarian = preferences?.includes('vegetarian') || preferences?.includes('vegan');
  const isKeto = preferences?.includes('keto');

  for (let day = 1; day <= 7; day++) {
    const dayMeals = {
      day,
      meals: {
        breakfast: {
          items: [
            {
              name: isKeto ? 'Avocado and eggs' : 'Oatmeal with fruits',
              quantity: '1 bowl',
              calories: isKeto ? 350 : 250,
              benefits: 'Healthy fats and protein',
            },
          ],
          totalCalories: isKeto ? 350 : 250,
          preparation: 'Simple assembly',
          timing: '7-8 AM',
        },
        lunch: {
          items: [
            {
              name: isVegetarian ? 'Quinoa salad with vegetables' : 'Grilled chicken salad',
              quantity: '1 plate',
              calories: 400,
              benefits: 'Balanced nutrition',
            },
          ],
          totalCalories: 400,
          preparation: '15 minutes',
          timing: '12-1 PM',
        },
        dinner: {
          items: [
            {
              name: isVegetarian ? 'Lentil soup with vegetables' : 'Fish with steamed vegetables',
              quantity: '1 serving',
              calories: 350,
              benefits: 'Light and nutritious',
            },
          ],
          totalCalories: 350,
          preparation: '20 minutes',
          timing: '7-8 PM',
        },
        snacks: [
          {
            name: 'Greek yogurt with nuts',
            quantity: '1 cup',
            calories: 200,
            timing: '4 PM',
            benefits: 'Protein and healthy fats',
          },
        ],
      },
      totalDailyCalories: 1300,
      nutritionalGoals: {
        protein: 80,
        carbs: 150,
        fats: 50,
        fiber: 25,
        vitamins: ['Vitamin C', 'Vitamin D', 'Calcium'],
      },
      hydration: {
        waterIntake: 8,
        herbalTeas: ['Green tea', 'Chamomile'],
      },
    };

    meals.push(dayMeals);
  }

  return meals;
};
