/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessHubRouteImport } from './routes/wellness-hub'
import { Route as SymptomCheckerRouteImport } from './routes/symptom-checker'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DietPlannerRouteImport } from './routes/diet-planner'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoCallAppointmentIdRouteImport } from './routes/video-call.$appointmentId'
import { Route as DoctorIdRouteImport } from './routes/doctor.$id'
import { Route as DashboardPatientRouteImport } from './routes/dashboard.patient'
import { Route as DashboardDoctorRouteImport } from './routes/dashboard.doctor'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const WellnessHubRoute = WellnessHubRouteImport.update({
  id: '/wellness-hub',
  path: '/wellness-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomCheckerRoute = SymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DietPlannerRoute = DietPlannerRouteImport.update({
  id: '/diet-planner',
  path: '/diet-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoCallAppointmentIdRoute = VideoCallAppointmentIdRouteImport.update({
  id: '/video-call/$appointmentId',
  path: '/video-call/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIdRoute = DoctorIdRouteImport.update({
  id: '/doctor/$id',
  path: '/doctor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatientRoute = DashboardPatientRouteImport.update({
  id: '/dashboard/patient',
  path: '/dashboard/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDoctorRoute = DashboardDoctorRouteImport.update({
  id: '/dashboard/doctor',
  path: '/dashboard/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/chatbot': typeof ChatbotRoute
  '/contact': typeof ContactRoute
  '/diet-planner': typeof DietPlannerRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/wellness-hub': typeof WellnessHubRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/video-call/$appointmentId': typeof VideoCallAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/chatbot': typeof ChatbotRoute
  '/contact': typeof ContactRoute
  '/diet-planner': typeof DietPlannerRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/wellness-hub': typeof WellnessHubRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/video-call/$appointmentId': typeof VideoCallAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/chatbot': typeof ChatbotRoute
  '/contact': typeof ContactRoute
  '/diet-planner': typeof DietPlannerRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/wellness-hub': typeof WellnessHubRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/doctor': typeof DashboardDoctorRoute
  '/dashboard/patient': typeof DashboardPatientRoute
  '/doctor/$id': typeof DoctorIdRoute
  '/video-call/$appointmentId': typeof VideoCallAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appointment'
    | '/chatbot'
    | '/contact'
    | '/diet-planner'
    | '/doctors'
    | '/login'
    | '/profile'
    | '/register'
    | '/symptom-checker'
    | '/wellness-hub'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/doctor/$id'
    | '/video-call/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/chatbot'
    | '/contact'
    | '/diet-planner'
    | '/doctors'
    | '/login'
    | '/profile'
    | '/register'
    | '/symptom-checker'
    | '/wellness-hub'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/doctor/$id'
    | '/video-call/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appointment'
    | '/chatbot'
    | '/contact'
    | '/diet-planner'
    | '/doctors'
    | '/login'
    | '/profile'
    | '/register'
    | '/symptom-checker'
    | '/wellness-hub'
    | '/dashboard/admin'
    | '/dashboard/doctor'
    | '/dashboard/patient'
    | '/doctor/$id'
    | '/video-call/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppointmentRoute: typeof AppointmentRoute
  ChatbotRoute: typeof ChatbotRoute
  ContactRoute: typeof ContactRoute
  DietPlannerRoute: typeof DietPlannerRoute
  DoctorsRoute: typeof DoctorsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SymptomCheckerRoute: typeof SymptomCheckerRoute
  WellnessHubRoute: typeof WellnessHubRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardDoctorRoute: typeof DashboardDoctorRoute
  DashboardPatientRoute: typeof DashboardPatientRoute
  DoctorIdRoute: typeof DoctorIdRoute
  VideoCallAppointmentIdRoute: typeof VideoCallAppointmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness-hub': {
      id: '/wellness-hub'
      path: '/wellness-hub'
      fullPath: '/wellness-hub'
      preLoaderRoute: typeof WellnessHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-checker': {
      id: '/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof SymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet-planner': {
      id: '/diet-planner'
      path: '/diet-planner'
      fullPath: '/diet-planner'
      preLoaderRoute: typeof DietPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-call/$appointmentId': {
      id: '/video-call/$appointmentId'
      path: '/video-call/$appointmentId'
      fullPath: '/video-call/$appointmentId'
      preLoaderRoute: typeof VideoCallAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/$id': {
      id: '/doctor/$id'
      path: '/doctor/$id'
      fullPath: '/doctor/$id'
      preLoaderRoute: typeof DoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/patient': {
      id: '/dashboard/patient'
      path: '/dashboard/patient'
      fullPath: '/dashboard/patient'
      preLoaderRoute: typeof DashboardPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/doctor': {
      id: '/dashboard/doctor'
      path: '/dashboard/doctor'
      fullPath: '/dashboard/doctor'
      preLoaderRoute: typeof DashboardDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppointmentRoute: AppointmentRoute,
  ChatbotRoute: ChatbotRoute,
  ContactRoute: ContactRoute,
  DietPlannerRoute: DietPlannerRoute,
  DoctorsRoute: DoctorsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SymptomCheckerRoute: SymptomCheckerRoute,
  WellnessHubRoute: WellnessHubRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardDoctorRoute: DashboardDoctorRoute,
  DashboardPatientRoute: DashboardPatientRoute,
  DoctorIdRoute: DoctorIdRoute,
  VideoCallAppointmentIdRoute: VideoCallAppointmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
